export enum Constants {
    LOGGER = 'LOGGER',
    CONFIG_SERVICE = 'CONFIG_SERVICE',
    HOME_CONTROLLER = 'HOME_CONTROLLER',
    DRONE_CONTROLLER = 'DRONE_CONTROLLER',
    DRONE_SERVICE = 'DRONE_SERVICE',
    DRONE_REPOSITORY = 'DRONE_REPOSITORY',
}
